name: Publish to npm and GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # 配置 npm 认证（包括 GitHub 和 npm）
      - name: Configure yarn registry and authenticate
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      # 安装依赖
      - name: Install dependencies with yarn
        run: yarn install

      # 构建项目
      - name: Build project with yarn
        run: yarn build

      # 如果打了tag，则发布到 GitHub Packages 和 npm
      - name: Publish to GitHub Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish --registry=https://npm.pkg.github.com

      - name: Publish to npm 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --registry=https://registry.npmjs.org
